### ISSUE TITLE
Aspect ratio controller

### ISSUE THREAD

**Issue by mpfoster** [onemoonsci/analystgui#4]
NMRViewJ has an aspect ratio control slider that allows one to easily scale a spectrum without resizing the window; makes it easy render round cross peaks. This, or something like it, would be nice to have in NMRFx. Separately adjusting the width and height of the spectrum could do the trick too, but currently that's limited in the `Attributes` `Style` tab to a few border values.

**Comment by brucejohnson** [comment]
Aspect controls added to Spectrum Attributes panel in version 10.3.85
